export default {
  "login": "Asensio0227",
  "id": 83821620,
  "node_id": "MDQ6VXNlcjgzODIxNjIw",
  "avatar_url": "https://avatars.githubusercontent.com/u/83821620?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Asensio0227",
  "html_url": "https://github.com/Asensio0227",
  "followers_url": "https://api.github.com/users/Asensio0227/followers",
  "following_url": "https://api.github.com/users/Asensio0227/following{/other_user}",
  "gists_url": "https://api.github.com/users/Asensio0227/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Asensio0227/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Asensio0227/subscriptions",
  "organizations_url": "https://api.github.com/users/Asensio0227/orgs",
  "repos_url": "https://api.github.com/users/Asensio0227/repos",
  "events_url": "https://api.github.com/users/Asensio0227/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Asensio0227/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Asensio",
  "company": null,
  "blog": "",
  "location": "Johannesburg South Africa",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": "Brendon52262477",
  "public_repos": 48,
  "public_gists": 0,
  "followers": 13,
  "following": 250,
  "created_at": "2021-05-07T12:34:17Z",
  "updated_at": "2022-07-25T20:28:01Z"
}
