const mockFollowers = [
  {
    "login": "sakiKnin",
    "id": 626946,
    "node_id": "MDQ6VXNlcjYyNjk0Ng==",
    "avatar_url": "https://avatars.githubusercontent.com/u/626946?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sakiKnin",
    "html_url": "https://github.com/sakiKnin",
    "followers_url": "https://api.github.com/users/sakiKnin/followers",
    "following_url": "https://api.github.com/users/sakiKnin/following{/other_user}",
    "gists_url": "https://api.github.com/users/sakiKnin/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sakiKnin/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sakiKnin/subscriptions",
    "organizations_url": "https://api.github.com/users/sakiKnin/orgs",
    "repos_url": "https://api.github.com/users/sakiKnin/repos",
    "events_url": "https://api.github.com/users/sakiKnin/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sakiKnin/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "vivekweb2013",
    "id": 7036736,
    "node_id": "MDQ6VXNlcjcwMzY3MzY=",
    "avatar_url": "https://avatars.githubusercontent.com/u/7036736?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/vivekweb2013",
    "html_url": "https://github.com/vivekweb2013",
    "followers_url": "https://api.github.com/users/vivekweb2013/followers",
    "following_url": "https://api.github.com/users/vivekweb2013/following{/other_user}",
    "gists_url": "https://api.github.com/users/vivekweb2013/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/vivekweb2013/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/vivekweb2013/subscriptions",
    "organizations_url": "https://api.github.com/users/vivekweb2013/orgs",
    "repos_url": "https://api.github.com/users/vivekweb2013/repos",
    "events_url": "https://api.github.com/users/vivekweb2013/events{/privacy}",
    "received_events_url": "https://api.github.com/users/vivekweb2013/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "yihuaxiang",
    "id": 7598734,
    "node_id": "MDQ6VXNlcjc1OTg3MzQ=",
    "avatar_url": "https://avatars.githubusercontent.com/u/7598734?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/yihuaxiang",
    "html_url": "https://github.com/yihuaxiang",
    "followers_url": "https://api.github.com/users/yihuaxiang/followers",
    "following_url": "https://api.github.com/users/yihuaxiang/following{/other_user}",
    "gists_url": "https://api.github.com/users/yihuaxiang/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/yihuaxiang/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/yihuaxiang/subscriptions",
    "organizations_url": "https://api.github.com/users/yihuaxiang/orgs",
    "repos_url": "https://api.github.com/users/yihuaxiang/repos",
    "events_url": "https://api.github.com/users/yihuaxiang/events{/privacy}",
    "received_events_url": "https://api.github.com/users/yihuaxiang/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "armancodv",
    "id": 9363099,
    "node_id": "MDQ6VXNlcjkzNjMwOTk=",
    "avatar_url": "https://avatars.githubusercontent.com/u/9363099?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/armancodv",
    "html_url": "https://github.com/armancodv",
    "followers_url": "https://api.github.com/users/armancodv/followers",
    "following_url": "https://api.github.com/users/armancodv/following{/other_user}",
    "gists_url": "https://api.github.com/users/armancodv/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/armancodv/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/armancodv/subscriptions",
    "organizations_url": "https://api.github.com/users/armancodv/orgs",
    "repos_url": "https://api.github.com/users/armancodv/repos",
    "events_url": "https://api.github.com/users/armancodv/events{/privacy}",
    "received_events_url": "https://api.github.com/users/armancodv/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "m0rp43us",
    "id": 12621034,
    "node_id": "MDQ6VXNlcjEyNjIxMDM0",
    "avatar_url": "https://avatars.githubusercontent.com/u/12621034?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/m0rp43us",
    "html_url": "https://github.com/m0rp43us",
    "followers_url": "https://api.github.com/users/m0rp43us/followers",
    "following_url": "https://api.github.com/users/m0rp43us/following{/other_user}",
    "gists_url": "https://api.github.com/users/m0rp43us/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/m0rp43us/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/m0rp43us/subscriptions",
    "organizations_url": "https://api.github.com/users/m0rp43us/orgs",
    "repos_url": "https://api.github.com/users/m0rp43us/repos",
    "events_url": "https://api.github.com/users/m0rp43us/events{/privacy}",
    "received_events_url": "https://api.github.com/users/m0rp43us/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "anbgsl1110",
    "id": 20208270,
    "node_id": "MDQ6VXNlcjIwMjA4Mjcw",
    "avatar_url": "https://avatars.githubusercontent.com/u/20208270?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/anbgsl1110",
    "html_url": "https://github.com/anbgsl1110",
    "followers_url": "https://api.github.com/users/anbgsl1110/followers",
    "following_url": "https://api.github.com/users/anbgsl1110/following{/other_user}",
    "gists_url": "https://api.github.com/users/anbgsl1110/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/anbgsl1110/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/anbgsl1110/subscriptions",
    "organizations_url": "https://api.github.com/users/anbgsl1110/orgs",
    "repos_url": "https://api.github.com/users/anbgsl1110/repos",
    "events_url": "https://api.github.com/users/anbgsl1110/events{/privacy}",
    "received_events_url": "https://api.github.com/users/anbgsl1110/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "akshaynarisetti",
    "id": 58532023,
    "node_id": "MDQ6VXNlcjU4NTMyMDIz",
    "avatar_url": "https://avatars.githubusercontent.com/u/58532023?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/akshaynarisetti",
    "html_url": "https://github.com/akshaynarisetti",
    "followers_url": "https://api.github.com/users/akshaynarisetti/followers",
    "following_url": "https://api.github.com/users/akshaynarisetti/following{/other_user}",
    "gists_url": "https://api.github.com/users/akshaynarisetti/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/akshaynarisetti/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/akshaynarisetti/subscriptions",
    "organizations_url": "https://api.github.com/users/akshaynarisetti/orgs",
    "repos_url": "https://api.github.com/users/akshaynarisetti/repos",
    "events_url": "https://api.github.com/users/akshaynarisetti/events{/privacy}",
    "received_events_url": "https://api.github.com/users/akshaynarisetti/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "mattnix4",
    "id": 60849130,
    "node_id": "MDQ6VXNlcjYwODQ5MTMw",
    "avatar_url": "https://avatars.githubusercontent.com/u/60849130?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mattnix4",
    "html_url": "https://github.com/mattnix4",
    "followers_url": "https://api.github.com/users/mattnix4/followers",
    "following_url": "https://api.github.com/users/mattnix4/following{/other_user}",
    "gists_url": "https://api.github.com/users/mattnix4/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mattnix4/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mattnix4/subscriptions",
    "organizations_url": "https://api.github.com/users/mattnix4/orgs",
    "repos_url": "https://api.github.com/users/mattnix4/repos",
    "events_url": "https://api.github.com/users/mattnix4/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mattnix4/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "MosFazli",
    "id": 69136464,
    "node_id": "MDQ6VXNlcjY5MTM2NDY0",
    "avatar_url": "https://avatars.githubusercontent.com/u/69136464?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/MosFazli",
    "html_url": "https://github.com/MosFazli",
    "followers_url": "https://api.github.com/users/MosFazli/followers",
    "following_url": "https://api.github.com/users/MosFazli/following{/other_user}",
    "gists_url": "https://api.github.com/users/MosFazli/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/MosFazli/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/MosFazli/subscriptions",
    "organizations_url": "https://api.github.com/users/MosFazli/orgs",
    "repos_url": "https://api.github.com/users/MosFazli/repos",
    "events_url": "https://api.github.com/users/MosFazli/events{/privacy}",
    "received_events_url": "https://api.github.com/users/MosFazli/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "chaudhurymousumi",
    "id": 80985027,
    "node_id": "MDQ6VXNlcjgwOTg1MDI3",
    "avatar_url": "https://avatars.githubusercontent.com/u/80985027?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/chaudhurymousumi",
    "html_url": "https://github.com/chaudhurymousumi",
    "followers_url": "https://api.github.com/users/chaudhurymousumi/followers",
    "following_url": "https://api.github.com/users/chaudhurymousumi/following{/other_user}",
    "gists_url": "https://api.github.com/users/chaudhurymousumi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/chaudhurymousumi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/chaudhurymousumi/subscriptions",
    "organizations_url": "https://api.github.com/users/chaudhurymousumi/orgs",
    "repos_url": "https://api.github.com/users/chaudhurymousumi/repos",
    "events_url": "https://api.github.com/users/chaudhurymousumi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/chaudhurymousumi/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "RafaelPrincival",
    "id": 82247772,
    "node_id": "MDQ6VXNlcjgyMjQ3Nzcy",
    "avatar_url": "https://avatars.githubusercontent.com/u/82247772?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/RafaelPrincival",
    "html_url": "https://github.com/RafaelPrincival",
    "followers_url": "https://api.github.com/users/RafaelPrincival/followers",
    "following_url": "https://api.github.com/users/RafaelPrincival/following{/other_user}",
    "gists_url": "https://api.github.com/users/RafaelPrincival/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/RafaelPrincival/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/RafaelPrincival/subscriptions",
    "organizations_url": "https://api.github.com/users/RafaelPrincival/orgs",
    "repos_url": "https://api.github.com/users/RafaelPrincival/repos",
    "events_url": "https://api.github.com/users/RafaelPrincival/events{/privacy}",
    "received_events_url": "https://api.github.com/users/RafaelPrincival/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Naline786",
    "id": 92000728,
    "node_id": "U_kgDOBXvR2A",
    "avatar_url": "https://avatars.githubusercontent.com/u/92000728?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Naline786",
    "html_url": "https://github.com/Naline786",
    "followers_url": "https://api.github.com/users/Naline786/followers",
    "following_url": "https://api.github.com/users/Naline786/following{/other_user}",
    "gists_url": "https://api.github.com/users/Naline786/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Naline786/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Naline786/subscriptions",
    "organizations_url": "https://api.github.com/users/Naline786/orgs",
    "repos_url": "https://api.github.com/users/Naline786/repos",
    "events_url": "https://api.github.com/users/Naline786/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Naline786/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "JacquesKellerman",
    "id": 97241128,
    "node_id": "U_kgDOBcvIKA",
    "avatar_url": "https://avatars.githubusercontent.com/u/97241128?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/JacquesKellerman",
    "html_url": "https://github.com/JacquesKellerman",
    "followers_url": "https://api.github.com/users/JacquesKellerman/followers",
    "following_url": "https://api.github.com/users/JacquesKellerman/following{/other_user}",
    "gists_url": "https://api.github.com/users/JacquesKellerman/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/JacquesKellerman/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/JacquesKellerman/subscriptions",
    "organizations_url": "https://api.github.com/users/JacquesKellerman/orgs",
    "repos_url": "https://api.github.com/users/JacquesKellerman/repos",
    "events_url": "https://api.github.com/users/JacquesKellerman/events{/privacy}",
    "received_events_url": "https://api.github.com/users/JacquesKellerman/received_events",
    "type": "User",
    "site_admin": false
  }
];

export default mockFollowers;